import {loadKnowledgeFile} from './knowledge-loader.mjs';
import {validateKnowledge} from './life.mjs';
import {readKnowledge,writeKnowledge} from './knowledge-store.mjs';
import {mountAccount} from './account.mjs';
import {mountWorkspace,renderPanorama} from './workspace.mjs';
import {options,answerKeys,grade,filterUnits,addTask,decision} from './models.mjs';
import {weekDates,eventsOn,conflicts,toICS,parseSchedule,excludeOccurrence,detachOccurrence} from './calendar.mjs';
const $=id=>document.getElementById(id);
const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
const names={home:'今天，從一件重要的事開始。',library:'把散落的知識，找回來。',cards:'用自己的話，真正記住。',quiz:'用題目，確認理解。',decision:'把狀況，整理成下一步。',calendar:'把時間，留給重要的事。',plans:'從目標，走到下一步。',journal:'把經驗，留下來。',review:'每週，校準一次方向。',finance:'讓每一筆錢，有跡可循。',settings:'保留資料，也保留選擇。'};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const cloudConfig=await fetch('./cloud-config.json').then(r=>r.json()).catch(()=>({enabled:false}));
let storageKey=cloudConfig.enabled?'college-os-guest':'college-os-v1';
let userLoggedIn=!cloudConfig.enabled;
let state=read(storageKey,{tasks:{},wrong:[],mastery:{},events:[]});
state.tasks??={};state.wrong??=[];state.mastery??={};state.events??=[];
const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(state,(key,value)=>key==='privateUnits'?undefined:value));document.dispatchEvent(new Event('college-saved'));}catch{$('task-message').textContent='瀏覽器無法儲存紀錄；請匯出備份。';}};
let builtinUnits=[],units=[],cards=[],questions=[],cardIndex=0,quizIndex=0,limit=24,selectedWeek=today,schedule=null;
$('today').textContent=new Date().toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei',month:'long',day:'numeric',weekday:'long'});
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function page(id){if(cloudConfig.enabled&&!userLoggedIn&&id!=='settings')id='settings';document.querySelectorAll('.page').forEach(node=>node.hidden=node.id!==id);document.querySelectorAll('nav button').forEach(node=>node.classList.toggle('active',node.dataset.page===id));$('page-title').textContent=names[id];if(id==='calendar')renderCalendar();}
mountWorkspace(state,save,refreshState);
document.querySelectorAll('[data-page],[data-open]').forEach(button=>button.addEventListener('click',()=>page(button.dataset.page??button.dataset.open)));
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export-progress').onclick=()=>download(`college-os-${today}.json`,JSON.stringify(state,null,2));
function renderTasks(){const tasks=state.tasks[today]??[];$('task-count').textContent=`${tasks.filter(t=>t.done).length} / ${tasks.length}（上限 4）`;$('tasks').replaceChildren();if(!tasks.length)$('tasks').append(el('p','今天還沒有主要任務。選一件最重要的事開始。','empty'));tasks.forEach(task=>{const row=el('div',undefined,'task'+(task.done?' done':''));const check=el('input');check.type='checkbox';check.checked=task.done;check.setAttribute('aria-label',`完成 ${task.title}`);check.onchange=()=>{task.done=check.checked;save();renderTasks();};const remove=el('button','移除');remove.onclick=()=>{state.tasks[today]=tasks.filter(t=>t.id!==task.id);save();renderTasks();};row.append(check,el('span',task.title),remove);$('tasks').append(row);});}
$('task-form').onsubmit=event=>{event.preventDefault();try{state.tasks[today]=addTask(state.tasks[today]??[],$('task-input').value);$('task-input').value='';$('task-message').textContent='';save();renderTasks();}catch(error){$('task-message').textContent=error.message;}};
function sourceText(unit){return `來源：${unit.sources.map(s=>s.file).join('、')} · 尚未逐項核對`;}
function details(unit){const container=$('detail-body');container.replaceChildren(el('span','來源待核對','tag'),el('h2',unit.title));const record=unit.original_record;container.append(el('p',unit.category??'未分類','tag'));if(unit.core_concept)container.append(el('pre',unit.core_concept));if(unit.solution_methods)container.append(el('pre',unit.solution_methods));if(unit.kind==='formula')container.append(el('p','此條目包含來源中的公式或自訂模型，未確認其有效性；不可直接用於判定他人或個人投資。'));for(const [title,key] of [['核心概念','analysis'],['理解','findings'],['流程','pipeline'],['名詞','glossary'],['方法','techniques'],['解釋','explanation'],['筆記','items'],['背面','back']])if(record[key])container.append(el('h3',title),el('pre',typeof record[key]==='string'?record[key]:JSON.stringify(record[key],null,2)));if(unit.kind==='question'){container.append(el('h3','選項'));options(record).forEach(([key,text])=>container.append(el('p',text)));container.append(el('p',`答案：${answerKeys(record).join('、')}`));}container.append(el('p',sourceText(unit),'source'));$('detail').showModal();}
$('close-detail').onclick=()=>$('detail').close();
function renderLibrary(){const filtered=filterUnits(units,$('search').value,$('kind').value).filter(u=>!$('category').value||u.category===$('category').value);$('results-count').textContent=`找到 ${filtered.length} 個單元 · 顯示前 ${Math.min(limit,filtered.length)} 個`;$('results').replaceChildren();filtered.slice(0,limit).forEach(unit=>{const node=el('button',undefined,'unit');node.append(el('span',({concept:'概念',question:'題目',note:'筆記',flashcard:'翻讀卡',research:'研究摘要',formula:'公式／模型'})[unit.kind]??unit.kind,'tag'),el('h3',unit.title),el('p',(unit.core_concept||unit.original_record.explanation||'點開查看內容與原始來源。').slice(0,110)),el('p',sourceText(unit),'source'));node.onclick=()=>details(unit);$('results').append(node);});$('more-results').hidden=limit>=filtered.length;}
['search','kind','category'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{limit=24;renderLibrary();}));$('more-results').onclick=()=>{limit+=24;renderLibrary();};
function renderCard(){if(!cards.length){$('card-front').textContent='尚無翻讀卡';return;}const unit=cards[cardIndex%cards.length];$('card-position').textContent=`主動回想 ${cardIndex%cards.length+1} / ${cards.length}`;$('card-front').textContent=unit.front;$('card-back').textContent=unit.back;$('card-back').hidden=true;$('flip').textContent='顯示答案';$('card-source').textContent=sourceText(unit);$('card-status').textContent=state.mastery[unit.id]==='known'?'上次標記：已能自行解釋':'';}
$('flip').onclick=()=>{$('card-back').hidden=!$('card-back').hidden;$('flip').textContent=$('card-back').hidden?'顯示答案':'收起答案';};$('card-next').onclick=()=>{cardIndex++;renderCard();};['card-again','card-known'].forEach(id=>$(id).onclick=()=>{if(!cards.length)return;state.mastery[cards[cardIndex%cards.length].id]=id==='card-known'?'known':'again';save();cardIndex++;renderCard();});
function quizPool(){return questions.filter(unit=>$('quiz-domain').value==='all'||($('quiz-domain').value==='wrong'?state.wrong.includes(unit.id):$('quiz-domain').value==='cs'?unit.sources[0].file.includes('第0'):unit.sources[0].file==='questions_50.json'));}
function renderQuiz(){const pool=quizPool();$('quiz-options').replaceChildren();$('quiz-feedback').hidden=true;$('quiz-submit').disabled=!pool.length;$('quiz-next').disabled=!pool.length;if(!pool.length){$('quiz-question').textContent='這個範圍目前沒有題目。';$('quiz-source').textContent='';$('quiz-position').textContent='';return;}const unit=pool[quizIndex%pool.length],record=unit.original_record;$('quiz-position').textContent=`第 ${quizIndex%pool.length+1} / ${pool.length} 題`;$('quiz-question').textContent=record.question??unit.title;options(record).forEach(([key,text])=>{const label=el('label');const input=el('input');input.type=answerKeys(record).length>1?'checkbox':'radio';input.name='answer';input.value=key;label.append(input,el('span',text));$('quiz-options').append(label);});$('quiz-source').textContent=sourceText(unit);}
$('quiz-form').onsubmit=event=>{event.preventDefault();const pool=quizPool();if(!pool.length)return;const unit=pool[quizIndex%pool.length],selected=[...document.querySelectorAll('#quiz-options input:checked')].map(input=>input.value);if(!selected.length){$('quiz-feedback').textContent='先選擇答案，再核對。';$('quiz-feedback').hidden=false;return;}const correct=grade(unit.original_record,selected);if(correct===null){$('quiz-feedback').textContent='這題缺少答案，尚不能評分。';}else{state.wrong=state.wrong.filter(id=>id!==unit.id);if(!correct)state.wrong.push(unit.id);state.attempts.push({id:crypto.randomUUID(),date:today,unitId:unit.id,correct,domain:unit.category});save();$('quiz-feedback').textContent=`${correct?'答對了。':'這題先放進錯題。'} 正解：${answerKeys(unit.original_record).join('、')}\n\n${unit.original_record.explanation??'這題尚無解釋。'}\n\n這是資料中的答案，尚未逐項核對。`;}$('quiz-feedback').hidden=false;$('quiz-submit').disabled=true;};$('quiz-next').onclick=()=>{quizIndex++;renderQuiz();};$('quiz-domain').onchange=()=>{quizIndex=0;renderQuiz();};
$('decision-form').onsubmit=event=>{event.preventDefault();const result=decision($('situation').value,$('energy').value,$('goal').value);const node=$('decision-result');node.replaceChildren(el('h3','下一步'));if(result.hints.length)node.append(el('p',`可能包含推測或評價的詞：${result.hints.join('、')}。請核對語境，這不代表你說錯。`));const list=el('ol');result.steps.forEach(step=>list.append(el('li',step)));node.append(list,el('p','事實狀態：尚未核實。此功能不推斷人格或說謊風險。'));node.hidden=false;};
function startEventEdit(item,date,onlyThis=false){editingEvent=onlyThis?null:item._seriesId??item.id;editingOccurrence=onlyThis?{seriesId:item._seriesId,date}:null;for(const [id,key] of [['event-title','title'],['event-start','start'],['event-end','end'],['event-category','category']])$(id).value=item[key]??'';$('event-date').value=onlyThis?date:(item.from??item.date??date);$('event-repeat').checked=!onlyThis&&item.weekday!==undefined;$('event-repeat').disabled=onlyThis;$('event-until').value=item.until??date;$('event-form-status').textContent='正在編輯：'+item.title+(onlyThis?'（只修改這一天）':'');$('detail').close();$('event-title').focus();}
function renderCalendar(){if(!schedule)return;const dates=weekDates(selectedWeek);$('calendar-range').textContent=`${dates[0]} — ${dates[6]}`;renderPanorama($('week-grid'),dates,state.events,(item,date)=>{const body=$('detail-body');body.replaceChildren(el('h2',item.title),el('p',`${date} ${item.start??'全天'} ${item.end??''}`),el('p',item.notes??''));if(item.status==='draft')body.append(el('p','依文件匯入，日期與內容待核對。'));if(item._seriesId){const editOne=el('button','只修改這一天','secondary');editOne.onclick=()=>startEventEdit(item,date,true);body.append(editOne);}const edit=el('button',item._seriesId?'編輯整個週期':'編輯此事件','secondary');edit.onclick=()=>startEventEdit(item,date,false);const remove=el('button',item._seriesId?'刪除此一天':'刪除此事件','secondary');remove.onclick=()=>{if(!confirm(item._seriesId?'只刪除 '+date+' 這一天的行程？':'確認刪除此事件？'))return;state.events=item._seriesId?excludeOccurrence(state.events,item._seriesId,date):state.events.filter(e=>e.id!==item.id);save();$('detail').close();renderCalendar();};if(item._seriesId){const removeSeries=el('button','刪除整個週期','secondary');removeSeries.onclick=()=>{if(!confirm('確認刪除整個重複週期？'))return;state.events=state.events.filter(e=>e.id!==item._seriesId);save();$('detail').close();renderCalendar();};body.append(edit,remove,removeSeries);}else body.append(edit,remove);$('detail').showModal();});const week=schedule.weeks.find(w=>dates[0]>=w.start&&dates[0]<=w.end);$('week-note').textContent=week?`第 ${week.number} 週：${week.title}。${week.focus}（文件規劃，非官方校曆）`:'一週一張全景表。跨時段事件依開始時間放入格子，時數仍計入完整事件。';}
let editingEvent=null,editingOccurrence=null;
['prev-week','next-week'].forEach(id=>$(id).onclick=()=>{const date=new Date(selectedWeek+'T12:00:00+08:00');date.setUTCDate(date.getUTCDate()+(id==='prev-week'?-7:7));selectedWeek=date.toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});renderCalendar();});$('calendar-today').onclick=()=>{selectedWeek=today;renderCalendar();};
$('import-schedule').onclick=()=>$('calendar-file').click();
$('calendar-file').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw new Error('作息檔不可超過 2 MB。');const imported=parseSchedule(await file.text());schedule=imported;state.schedule=imported;const ids=new Set(state.events.map(item=>item.id));state.events.push(...imported.events.filter(item=>!ids.has(item.id)));save();renderCalendar();$('calendar-status').textContent=`已從本機匯入 ${imported.events.length} 個事件；資料只存於此瀏覽器，未上傳 GitHub。日期仍需核對。`;}catch(error){$('calendar-status').textContent='匯入失敗：'+error.message;}finally{event.target.value='';}};
$('event-form').onsubmit=event=>{event.preventDefault();const start=$('event-start').value,end=$('event-end').value;if(start&&end&&end<=start){$('calendar-status').textContent='結束時間必須晚於開始時間。';return;}const item={id:editingEvent??crypto.randomUUID(),title:$('event-title').value.trim(),date:$('event-date').value,start,end,category:$('event-category').value,status:'personal',source:'自行新增'};if($('event-repeat').checked){const until=$('event-until').value;if(!until||until<item.date){$('calendar-status').textContent='請填寫有效的重複截止日期。';return;}item.weekday=new Date(item.date+'T12:00:00Z').getUTCDay();item.from=item.date;item.until=until;delete item.date;}if(editingOccurrence){state.events=detachOccurrence(state.events,editingOccurrence.seriesId,editingOccurrence.date,item);}else{state.events=state.events.filter(e=>e.id!==item.id);state.events.push(item);}save();selectedWeek=$('event-date').value;editingEvent=null;editingOccurrence=null;$('event-repeat').disabled=false;event.target.reset();$('event-form-status').textContent='';$('event-date').value=today;renderCalendar();$('calendar-status').textContent='事件已儲存在本機瀏覽器。';};$('cancel-event-edit').onclick=()=>{editingEvent=null;editingOccurrence=null;$('event-repeat').disabled=false;$('event-form').reset();$('event-date').value=today;$('event-form-status').textContent='';};
$('copy-week').onclick=()=>{const target=$('copy-week-date').value;if(!target)return;const sourceDates=weekDates(selectedWeek),targetDates=weekDates(target);if(sourceDates[0]===targetDates[0]){$('calendar-status').textContent='請選不同的一週。';return;}const copies=sourceDates.flatMap((d,i)=>eventsOn(state.events,d).filter(e=>e.weekday===undefined).map(e=>({...e,id:crypto.randomUUID(),date:targetDates[i],source:'複製自 '+d})));if(!copies.length){$('calendar-status').textContent='本週沒有單次事件可複製；週期事件會自行延伸，不重複複製。';return;}if(!confirm(`複製 ${copies.length} 個單次事件到 ${targetDates[0]} 這週？`))return;state.events.push(...copies);save();selectedWeek=target;renderCalendar();$('calendar-status').textContent='已複製；請查看是否有時間衝突。';};
$('export-calendar').onclick=()=>download('college-os-calendar.ics',toICS(state.events),'text/calendar');
async function init(){renderTasks();$('event-date').value=today;try{const manifest=await fetch('./data/index.json').then(r=>{if(!r.ok)throw new Error('找不到資料清單');return r.json();});units=(await Promise.all(manifest.files.map(file=>loadKnowledgeFile(file)))).flat();builtinUnits=[...units];state.privateUnits=await readKnowledge(storageKey).catch(()=>[]);units.push(...(state.privateUnits??[]).filter(u=>!units.some(x=>x.id===u.id)));setupKnowledge();questions=units.filter(unit=>unit.kind==='question');cards=units.filter(unit=>unit.kind==='flashcard'||unit.kind==='concept').map(unit=>({...unit,front:unit.kind==='flashcard'?unit.original_record.front:`請用自己的話解釋：${unit.title}`,back:unit.kind==='flashcard'?unit.original_record.back:[unit.core_concept,unit.solution_methods].filter(Boolean).join('\n\n')}));schedule=state.schedule??await fetch('./data/schedule.json').then(r=>r.json());$('unit-count').textContent=units.length;$('question-count').textContent=questions.length;renderLibrary();renderCard();renderQuiz();renderCalendar();}catch(error){$('load-error').hidden=false;$('load-error').textContent=`載入失敗：${error.message}。請使用 python3 run.py 啟動，直接打開 HTML 檔無法載入資料。`;}}
function setupKnowledge(){const select=$('category'),old=select.value;select.replaceChildren(el('option','所有分類'));select.firstChild.value='';[...new Set(units.map(u=>u.category??'未分類'))].sort().forEach(category=>{const opt=el('option',category);opt.value=category;select.append(opt);});select.value=old;}
$('export-knowledge').onclick=()=>download('college-os-knowledge-pack.json',JSON.stringify(units));
$('import-knowledge').onclick=()=>$('knowledge-file').click();$('knowledge-file').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>20e6)throw Error('知識包最多 20 MB。');const data=JSON.parse(await file.text());validateKnowledge(data);const ids=new Set(units.map(u=>u.id));const additions=data.filter(u=>!ids.has(u.id));const combined=[...(state.privateUnits??[]),...additions];await writeKnowledge(storageKey,combined);state.privateUnits=combined;units.push(...additions);save();setupKnowledge();questions=units.filter(u=>u.kind==='question');cards=units.filter(u=>u.kind==='flashcard'||u.kind==='concept').map(u=>({...u,front:u.kind==='flashcard'?u.original_record.front:'請解釋：'+u.title,back:u.kind==='flashcard'?u.original_record.back:u.core_concept}));renderLibrary();renderCard();renderQuiz();$('unit-count').textContent=units.length;$('question-count').textContent=questions.length;$('knowledge-status').textContent=`已匯入 ${additions.length} 筆，跳過已有 ID。`;}catch(error){$('knowledge-status').textContent=error.message;}finally{event.target.value='';}};
async function refreshState(){schedule=state.schedule??{weeks:[],events:[]};if(state.privateUnits)await writeKnowledge(storageKey,state.privateUnits);else state.privateUnits=await readKnowledge(storageKey).catch(()=>[]);units=[...builtinUnits,...state.privateUnits.filter(u=>!builtinUnits.some(x=>x.id===u.id))];setupKnowledge();questions=units.filter(u=>u.kind==='question');cards=units.filter(u=>u.kind==='flashcard'||u.kind==='concept').map(u=>({...u,front:u.kind==='flashcard'?u.original_record.front:'請解釋：'+u.title,back:u.kind==='flashcard'?u.original_record.back:u.core_concept}));$('unit-count').textContent=units.length;$('question-count').textContent=questions.length;renderLibrary();renderCard();renderQuiz();renderTasks();renderCalendar();document.dispatchEvent(new Event('college-saved'));}
await mountAccount(cloudConfig,state,{save,setStorageKey:key=>storageKey=key,setAuthenticated:value=>{userLoggedIn=value;page(value?'home':'settings');},refresh:refreshState});
if(cloudConfig.enabled&&!userLoggedIn)page('settings');
init();
