import {mountManagement} from './management-ui.mjs';
import {readable,topicOf,studyCard,mergeKnowledge,nextReview} from './study.mjs';
import {mountExperience} from './experience.mjs';
import {loadKnowledgeFile} from './knowledge-loader.mjs';
import {latexToReadable} from './math-format.mjs';
import {validateKnowledge,validDate} from './life.mjs';
import {readKnowledge,writeKnowledge} from './knowledge-store.mjs';
import {mountWorkspace,renderPanorama} from './workspace.mjs';
import {options,answerKeys,grade,filterUnits,addTask,decision} from './models.mjs';
import {weekDates,eventsOn,conflicts,toICS,parseSchedule,excludeOccurrence,detachOccurrence,workloadByDay} from './calendar.mjs';
import {createItemPdfExporter} from './pdf.mjs';
const $=id=>document.getElementById(id);
const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
const names={home:'今天，從一件重要的事開始。',library:'把散落的知識，找回來。',cards:'用自己的話，真正記住。',quiz:'用題目，確認理解。',decision:'決定下一步，開始累積。',calendar:'把時間，留給重要的事。',plans:'從目標，走到下一步。',journal:'把經驗，留下來。',review:'每週，校準一次方向。',finance:'讓每一筆錢，有跡可循。',settings:'保留資料，也保留選擇。'};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const storageKey='college-os-v1';
const exportItemPdf=createItemPdfExporter();
let state=read(storageKey,{tasks:{},wrong:[],mastery:{},events:[]});
state.tasks??={};state.wrong??=[];state.mastery??={};state.events??=[];state.focusSessions??=[];
state.wrongAnalysis??=[];
const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(state,(key,value)=>key==='privateUnits'?undefined:value));document.dispatchEvent(new Event('college-saved'));}catch{$('task-message').textContent='瀏覽器無法儲存紀錄；請匯出備份。';}};
let builtinUnits=[],units=[],cards=[],cardPool=[],cardSession=[],cardIndex=0,cardOutcomes={known:0,again:0,skip:0},questions=[],quizIndex=0,quizCurrentUnit=null,limit=24,selectedWeek=today,schedule=null,focusTask=null,focusTimer=null,focusRemaining=0,focusPlanned=0,focusFirstStep='',focusPrintRecord=null;
$('today').textContent=new Date().toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei',month:'long',day:'numeric',weekday:'long'});
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function page(id){document.querySelectorAll('.page').forEach(node=>node.hidden=node.id!==id);document.querySelectorAll('nav button').forEach(node=>node.classList.toggle('active',node.dataset.page===id));$('page-title').textContent=names[id];if(id==='calendar')renderCalendar();globalThis.window?.scrollTo?.({top:0,behavior:'instant'});}
mountWorkspace(state,save,refreshState,exportItemPdf);
document.querySelectorAll('[data-page],[data-open]').forEach(button=>button.addEventListener('click',()=>page(button.dataset.page??button.dataset.open)));
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export-progress').onclick=()=>download(`college-os-${today}.json`,JSON.stringify(state,null,2));
async function downloadKnowledgeResource(file,name,type){try{const response=await fetch('./data/'+file);if(!response.ok)throw Error();download(name,await response.text(),type);$('ai-format-status').textContent='已準備下載：'+name;}catch{$('ai-format-status').textContent='下載失敗，請確認程式資料夾完整。';}}
$('ai-download-template').onclick=()=>downloadKnowledgeResource('college-os-ai-template.json','college-os-ai-template.json','application/json');$('ai-download-schema').onclick=()=>downloadKnowledgeResource('college-os-ai-schema.json','college-os-ai-schema.json','application/schema+json');$('ai-download-prompt').onclick=()=>downloadKnowledgeResource('college-os-ai-instructions.txt','college-os-ai-instructions.txt','text/plain;charset=utf-8');
function renderTasks(){const tasks=state.tasks[today]??[];$('task-count').textContent=`${tasks.filter(t=>t.done).length} / ${tasks.length}（上限 4）`;$('tasks').replaceChildren();if(!tasks.length)$('tasks').append(el('p','今天還沒有主要任務。選一件最重要的事開始。','empty'));tasks.forEach(task=>{const row=el('div',undefined,'task'+(task.done?' done':''));const check=el('input');check.type='checkbox';check.checked=task.done;check.setAttribute('aria-label',`完成 ${task.title}`);check.onchange=()=>{task.done=check.checked;save();renderTasks();};const focus=el('button','開始專注','secondary');focus.type='button';focus.onclick=()=>openFocus(task);focus.disabled=task.done;const remove=el('button','移除');remove.onclick=()=>{state.tasks[today]=tasks.filter(t=>t.id!==task.id);save();renderTasks();};const pdf=el('button','存成 PDF','secondary');pdf.setAttribute('aria-label',`匯出任務：${task.title}`);pdf.onclick=()=>exportItemPdf(task.title,[['日期',today],['類型','今日任務'],['狀態',task.done?'已完成':'待完成']]);row.append(check,el('span',task.title),pdf,focus,remove);$('tasks').append(row);});}
function clockText(seconds){const minutes=Math.floor(Math.max(0,seconds)/60),remainder=Math.max(0,seconds)%60;return `${String(minutes).padStart(2,'0')}:${String(remainder).padStart(2,'0')}`;}
function updateFocusClock(){$('focus-clock').textContent=clockText(focusRemaining);}
function openFocus(task){focusTask=task;clearInterval(focusTimer);focusTimer=null;focusRemaining=0;focusPlanned=0;$('focus-task-title').textContent=task.title;$('focus-first-step').value='';$('focus-duration').value='25';$('focus-setup-error').textContent='';$('focus-setup').hidden=false;$('focus-running').hidden=true;$('focus-result').hidden=true;$('focus-close').textContent='關閉';$('focus-dialog').showModal();$('focus-first-step').focus();}
function beginFocus(){focusFirstStep=$('focus-first-step').value.trim();focusPlanned=Number($('focus-duration').value);if(!focusFirstStep){$('focus-setup-error').textContent='先寫下一個兩分鐘內能開始的動作。';$('focus-first-step').focus();return;}if(!Number.isInteger(focusPlanned)||focusPlanned<5||focusPlanned>120){$('focus-setup-error').textContent='專注時間請設在 5 至 120 分鐘。';$('focus-duration').focus();return;}$('focus-setup-error').textContent='';focusRemaining=focusPlanned*60;$('focus-first-step-view').textContent='第一步：'+focusFirstStep;$('focus-setup').hidden=true;$('focus-result').hidden=true;$('focus-running').hidden=false;$('focus-pause').textContent='暫停';$('focus-close').textContent='結束並儲存這段';updateFocusClock();focusTimer=setInterval(()=>{focusRemaining=Math.max(0,focusRemaining-1);updateFocusClock();if(focusRemaining===0)finishFocus(true);},1000);}
function finishFocus(completed=false){if(!focusTask||!focusPlanned)return;clearInterval(focusTimer);focusTimer=null;const actualSeconds=focusPlanned*60-focusRemaining;const session={id:crypto.randomUUID(),date:today,title:focusTask.title,firstStep:focusFirstStep,plannedMinutes:focusPlanned,actualSeconds,completed,finishedAt:new Date().toISOString()};state.focusSessions.push(session);focusPrintRecord=session;save();$('focus-running').hidden=true;$('focus-setup').hidden=true;$('focus-result').hidden=false;$('focus-close').textContent='關閉';$('focus-result-text').textContent=`已記錄 ${Math.floor(actualSeconds/60)} 分鐘專注時間。${completed?'這段時間完成了。':'先休息一下，再決定下一步。'}`;}
$('focus-start').onclick=beginFocus;$('focus-export').onclick=()=>{if(focusPrintRecord)exportItemPdf(focusPrintRecord.title,[['日期',focusPrintRecord.date],['第一步',focusPrintRecord.firstStep],['預計分鐘',focusPrintRecord.plannedMinutes],['實際分鐘',Math.floor(focusPrintRecord.actualSeconds/60)],['結果',focusPrintRecord.completed?'完成':'提前結束']]);};$('focus-pause').onclick=()=>{if(focusTimer){clearInterval(focusTimer);focusTimer=null;$('focus-pause').textContent='繼續';}else{focusTimer=setInterval(()=>{focusRemaining=Math.max(0,focusRemaining-1);updateFocusClock();if(focusRemaining===0)finishFocus(true);},1000);$('focus-pause').textContent='暫停';}};$('focus-finish').onclick=()=>finishFocus(false);$('focus-close').onclick=()=>{if(focusPlanned&&$('focus-result').hidden)finishFocus(false);$('focus-dialog').close();};$('focus-again').onclick=()=>{if(focusTask)openFocus(focusTask);};
$('task-form').onsubmit=event=>{event.preventDefault();try{state.tasks[today]=addTask(state.tasks[today]??[],$('task-input').value);$('task-input').value='';$('task-message').textContent='';save();renderTasks();}catch(error){$('task-message').textContent=error.message;}};
const evidenceLabel={verified_official:'官方來源已核對',cross_checked:'多來源已核對',unverified:'尚未逐項核對',ai_draft:'AI 草稿待審'};
function sourceText(unit){const sources=(unit.sources??[]).map(s=>s.file??s.reference??'來源未命名').join('、')||'未提供來源';return `來源：${sources} · ${evidenceLabel[unit.evidence_status]??'查證狀態未標示'}`;}
const mathPattern=/\\(?:times|cdot|frac|sqrt|mathrm|text|alpha|beta|gamma|Delta|partial|implies|leq|geq|neq|pi|sigma|sum|prod)\b|[A-Za-z][_^](?:\{|[0-9A-Za-z])/;
function displayText(value,forceMath=false){const text=readable(value);return forceMath||mathPattern.test(text)?latexToReadable(text):text;}
function detailValue(value,forceMath=false){const text=readable(value);const needsMath=forceMath||mathPattern.test(text);return el('pre',needsMath?latexToReadable(text):text,needsMath?'formula-value':'');}
function details(unit){const container=$('detail-body'),isFormula=unit.kind==='formula',statusText=evidenceLabel[unit.evidence_status]??'查證狀態未標示';container.replaceChildren(el('span',isFormula?`公式／模型 · ${statusText}`:statusText,'tag'),el('h2',unit.title));const record=unit.original_record;container.append(el('p',unit.category??'未分類','tag'));if(unit.core_concept)container.append(el('h3','核心概念'),detailValue(unit.core_concept,isFormula));if(unit.deep_understanding)container.append(el('h3','深度理解'),detailValue(unit.deep_understanding,isFormula));if(unit.solution_methods)container.append(el('h3','方法／公式'),detailValue(unit.solution_methods,isFormula));for(const [label,value] of [['範例',unit.examples],['反例',unit.counterexamples],['常見錯誤',unit.common_mistakes]])if(value?.length)container.append(el('h3',label),detailValue(value,isFormula));if(isFormula)container.append(el('p',`此筆公式／模型的狀態為「${statusText}」；使用前請確認變數定義與適用情境。`,'formula-note'));for(const [title,key] of [['核心概念','analysis'],['理解','findings'],['流程','pipeline'],['名詞','glossary'],['方法','techniques'],['解釋','explanation'],['筆記','items'],['背面','back']])if(record[key])container.append(el('h3',title),detailValue(record[key],isFormula));if(unit.kind==='question'){container.append(el('h3','選項'));options(record).forEach(([key,text])=>container.append(el('p',displayText(text))));container.append(el('p',`答案：${answerKeys(record).join('、')}`));}container.append(el('p',sourceText(unit),'source'));const exportButton=el('button','這筆資料存成 PDF','primary');exportButton.type='button';exportButton.onclick=()=>exportItemPdf(unit.title,[['類型',kindLabels[unit.kind]??unit.kind],['主題',unit.category??'未分類'],['核心概念',displayText(unit.core_concept,isFormula)],['深度理解',displayText(unit.deep_understanding,isFormula)],['解題／使用方法',displayText(unit.solution_methods,isFormula)],['完整原始資料',displayText(record,isFormula)],['來源與查證狀態',sourceText(unit)]]);container.append(exportButton);$('detail').showModal();}
$('close-detail').onclick=()=>$('detail').close();
function renderLibrary(){const filtered=filterUnits(units,$('search').value,$('kind').value).filter(u=>!$('category').value||u.category===$('category').value);$('results-count').textContent=`找到 ${filtered.length.toLocaleString()} 個單元 · 顯示前 ${Math.min(limit,filtered.length).toLocaleString()} 個`;$('results').replaceChildren();filtered.slice(0,limit).forEach(unit=>{const node=el('button',undefined,'unit'),preview=unit.core_concept||unit.deep_understanding||unit.original_record.explanation||'點開查看內容與原始來源。';node.append(el('span',({concept:'概念',question:'題目',note:'筆記',flashcard:'翻讀卡',research:'研究摘要',formula:'公式／模型'})[unit.kind]??unit.kind,'tag'),el('h3',unit.title),el('p',displayText(preview,unit.kind==='formula').slice(0,110)),el('p',sourceText(unit),'source'));node.onclick=()=>details(unit);$('results').append(node);});$('more-results').hidden=limit>=filtered.length;}
const kindLabels={concept:'概念',flashcard:'翻讀卡',question:'題目',note:'筆記',research:'研究摘要',formula:'公式／模型'};
function renderDistribution(container,rows,total){container.replaceChildren();if(!total||!rows.length){container.append(el('p','尚無可統計資料。','empty'));return;}const max=Math.max(1,...rows.map(row=>row.count));rows.forEach(row=>{const item=el('div',undefined,'distribution-row');const label=el('span',row.label,'distribution-label');const value=el('strong',`${row.count.toLocaleString()} · ${(row.count/total*100).toFixed(1)}%`,'distribution-value');const track=el('div',undefined,'distribution-track');track.setAttribute('role','img');track.setAttribute('aria-label',`${row.label} ${row.count} 個，佔 ${(row.count/total*100).toFixed(1)}%`);const fill=el('span',undefined,'distribution-fill');fill.style.width=`${row.count/max*100}%`;track.append(fill);item.append(label,value,track);container.append(item);});}
function renderKnowledgeDistribution(){const kinds=new Map(),topics=new Map();for(const unit of units){kinds.set(unit.kind,(kinds.get(unit.kind)||0)+1);const topic=unit.category||'未分類';topics.set(topic,(topics.get(topic)||0)+1);}const typeRows=[...kinds].map(([key,count])=>({label:kindLabels[key]??key,count})).sort((a,b)=>b.count-a.count);const allTopics=[...topics].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count);const visibleTopics=allTopics.slice(0,10);const other=allTopics.slice(10).reduce((sum,row)=>sum+row.count,0);if(other)visibleTopics.push({label:`其他主題（${allTopics.length-10} 個）`,count:other});$('knowledge-distribution-count').textContent=`${units.length.toLocaleString()} 個單元 · ${topics.size.toLocaleString()} 個主題`;$('knowledge-kind-chart').setAttribute('aria-label',`資料類型比例，共 ${units.length} 個單元`);$('knowledge-topic-chart').setAttribute('aria-label','知識主題比例，依數量排序');renderDistribution($('knowledge-kind-chart'),typeRows,units.length);renderDistribution($('knowledge-topic-chart'),visibleTopics,units.length);}

['search','kind','category'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{limit=24;renderLibrary();}));$('category-search').addEventListener('input',()=>{setupKnowledge();limit=24;renderLibrary();});$('more-results').onclick=()=>{limit+=24;renderLibrary();};
function updateCardTypeOptions(){const topic=$('card-topic').value,pool=cards.filter(unit=>topic==='__all__'||topicOf(unit)===topic),select=$('card-kind'),selected=select.value;select.replaceChildren();const first=el('option',topic?'全部卡片':'先選擇主題');first.value='all';select.append(first);const counts=new Map();for(const unit of pool)counts.set(unit.kind,(counts.get(unit.kind)||0)+1);for(const type of Object.keys(kindLabels))if(counts.has(type)){const option=el('option',`${kindLabels[type]}（${counts.get(type).toLocaleString()} 張）`);option.value=type;select.append(option);}select.disabled=!topic;select.value=[...counts.keys()].includes(selected)?selected:'all';$('card-topic-count').textContent=topic?`「${topic}」共 ${pool.length.toLocaleString()} 張卡；選擇類型後，每次只抽一小組。`:'先選一個主題，卡片不會一次全部展開。';$('card-session-start').disabled=!topic||pool.length===0;}
function setupCardTopics(){const select=$('card-topic'),old=select.value,query=$('card-topic-search').value.trim().toLocaleLowerCase(),counts=new Map();for(const unit of cards){const topic=unit.category||'未分類';counts.set(topic,(counts.get(topic)||0)+1);}select.replaceChildren();const placeholder=el('option','請先搜尋或選擇主題');placeholder.value='';select.append(placeholder);const all=el('option','所有主題 · '+cards.length+' 張');all.value='__all__';select.append(all);[...counts].filter(([topic])=>topic.toLocaleLowerCase().includes(query)).sort((a,b)=>a[0].localeCompare(b[0],'zh-Hant')).forEach(([topic,count])=>{const option=el('option',`${topic} · ${count.toLocaleString()} 張`);option.value=topic;select.append(option);});select.value=old==='__all__'?old:counts.has(old)&&(!query||old.toLocaleLowerCase().includes(query))?old:'';$('card-library-count').textContent=`${cards.length.toLocaleString()} 張可練`;updateCardTypeOptions();}
function shuffleCards(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
function startCardSession(){const topic=$('card-topic').value,type=$('card-kind').value,size=Number($('card-batch-size').value);cardPool=cards.filter(unit=>(topic==='__all__'||topicOf(unit)===topic)&&(type==='all'||unit.kind===type));const now=new Date().toISOString(),due=cardPool.filter(unit=>!state.reviewDue[unit.id]||state.reviewDue[unit.id].due<=now),source=due.length?due:cardPool;cardSession=shuffleCards(source).slice(0,Math.min(size,source.length));cardIndex=0;cardOutcomes={known:0,again:0,skip:0};renderCard();}
function renderCard(){if(!cardSession.length){$('card-empty').hidden=false;$('card-study').hidden=true;$('card-complete').hidden=true;return;}if(cardIndex>=cardSession.length){$('card-empty').hidden=true;$('card-study').hidden=true;$('card-complete').hidden=false;$('card-complete-summary').textContent=`本組 ${cardSession.length} 張：${cardOutcomes.known} 張已能自行解釋、${cardOutcomes.again} 張標記再練、${cardOutcomes.skip} 張跳過。想繼續可再抽一組。`;$('card-session-start').textContent='重新開始本次練習';return;}$('card-empty').hidden=true;$('card-study').hidden=false;$('card-complete').hidden=true;const unit=cardSession[cardIndex];$('card-position').textContent=`本次 ${cardIndex+1} / ${cardSession.length} 張 · ${unit.category||'未分類'} · ${kindLabels[unit.kind]??unit.kind}`;$('card-front').textContent=displayText(unit.front);$('card-back').textContent=displayText(unit.back);$('card-back').hidden=true;$('flip').textContent='顯示答案';$('card-source').textContent=sourceText(unit);$('card-export').hidden=false;$('card-status').textContent=state.mastery[unit.id]==='known'?'上次標記：已能自行解釋':state.mastery[unit.id]==='again'?'上次標記：還不熟':'第一次練習';$('card-batch-note').textContent=`本主題符合條件 ${cardPool.length.toLocaleString()} 張；這次抽出 ${cardSession.length} 張。`;$('card-session-start').textContent='重新抽一組';}
function advanceCard(outcome){const unit=cardSession[cardIndex];if(!unit)return;if(outcome){state.mastery[unit.id]=outcome;state.reviewDue[unit.id]=nextReview(state.reviewDue[unit.id],outcome);cardOutcomes[outcome]++;save();}else cardOutcomes.skip++;cardIndex++;renderCard();}
$('card-topic-search').oninput=()=>{const before=$('card-topic').value;setupCardTopics();if(before!==$('card-topic').value){cardSession=[];renderCard();}};$('card-topic').onchange=()=>{updateCardTypeOptions();cardSession=[];renderCard();};$('card-kind').onchange=()=>{cardSession=[];renderCard();};$('card-session-start').onclick=startCardSession;$('card-session-again').onclick=startCardSession;$('card-export').onclick=()=>{const unit=cardSession[cardIndex];if(unit)exportItemPdf(unit.title,[['主題',unit.category??'未分類'],['卡片正面',displayText(unit.front)],['卡片背面',displayText(unit.back)],['來源與查證狀態',sourceText(unit)]]);};$('flip').onclick=()=>{$('card-back').hidden=!$('card-back').hidden;$('flip').textContent=$('card-back').hidden?'顯示答案':'收起答案';};$('card-next').onclick=()=>advanceCard(null);$('card-again').onclick=()=>advanceCard('again');$('card-known').onclick=()=>advanceCard('known');

function quizPool(){const scope=$('quiz-domain').value;return questions.filter(u=>!$('quiz-search')||readable(u).toLocaleLowerCase().includes($('quiz-search').value.toLocaleLowerCase())).filter(unit=>scope==='all'||scope===''||(scope==='wrong'?state.wrong.includes(unit.id):scope.startsWith('topic:')?topicOf(unit)===scope.slice(6):scope==='cs'?(unit.sources?.[0]?.file??'').includes('第0'):unit.sources?.[0]?.file==='questions_50.json'));}
function renderQuiz(){quizCurrentUnit=null;const pool=quizPool();$('quiz-options').replaceChildren();$('quiz-feedback').hidden=true;$('quiz-submit').disabled=!pool.length;$('quiz-next').disabled=!pool.length;if(!pool.length){$('quiz-export').disabled=true;$('quiz-question').textContent='這個範圍目前沒有題目。';$('quiz-source').textContent='';$('quiz-position').textContent='';return;}const unit=pool[quizIndex%pool.length],record=unit.original_record;quizCurrentUnit=unit;$('quiz-position').textContent=`第 ${quizIndex%pool.length+1} / ${pool.length} 題`;$('quiz-question').textContent=displayText(record.question??unit.title);options(record).forEach(([key,text])=>{const label=el('label');const input=el('input');input.type=answerKeys(record).length>1?'checkbox':'radio';input.name='answer';input.value=key;label.append(input,el('span',displayText(text)));$('quiz-options').append(label);});$('quiz-source').textContent=sourceText(unit);$('quiz-export').disabled=false;}
$('quiz-form').onsubmit=event=>{event.preventDefault();const pool=quizPool();if(!pool.length)return;const unit=pool[quizIndex%pool.length],selected=[...document.querySelectorAll('#quiz-options input:checked')].map(input=>input.value);if(!selected.length){$('quiz-feedback').textContent='先選擇答案，再核對。';$('quiz-feedback').hidden=false;return;}const correct=grade(unit.original_record,selected);if(correct===null){$('quiz-feedback').textContent='這題缺少答案，尚不能評分。';}else{state.wrong=state.wrong.filter(id=>id!==unit.id);if(!correct)state.wrong.push(unit.id);const attempt={id:crypto.randomUUID(),date:today,unitId:unit.id,correct,domain:unit.category,selected:[...selected].sort(),answer:answerKeys(unit.original_record)};state.attempts.push(attempt);save();$('quiz-feedback').textContent=`${correct?'答對了。':'這題先放進錯題。'} 正解：${answerKeys(unit.original_record).join('、')}\n\n${displayText(unit.original_record.explanation??'這題尚無解釋。')}\n\n${evidenceLabel[unit.evidence_status]??'查證狀態未標示'}。`;if(!correct){const entry={id:crypto.randomUUID(),attemptId:attempt.id,unitId:unit.id,date:today,domain:unit.category,selected:attempt.selected,answer:attempt.answer,reason:'尚未分析',why:'',next:''};state.wrongAnalysis.push(entry);save();const form=el('form',undefined,'wrong-inline');form.append(el('strong','花 20 秒標記錯因'));const label=el('label','這題錯在哪裡？');const select=el('select');for(const [value,text] of [['尚未分析','先選錯因'],['概念不熟','概念不熟'],['題意看錯','題意看錯'],['選項混淆','選項混淆'],['公式／計算','公式／計算'],['記憶提取失敗','記憶提取失敗'],['粗心／時間壓力','粗心／時間壓力'],['其他','其他']]){const option=el('option',text);option.value=value;select.append(option);}select.value=entry.reason;label.append(select);form.append(label);const why=el('input');why.placeholder='我原本怎麼想？（選填）';why.maxLength=500;form.append(why);const next=el('input');next.placeholder='下次最小的補強動作（選填）';next.maxLength=300;form.append(next);const saveAnalysis=el('button','保存錯題分析','secondary');saveAnalysis.type='submit';form.append(saveAnalysis);form.onsubmit=e=>{e.preventDefault();entry.reason=select.value;entry.why=why.value.trim();entry.next=next.value.trim();save();};$('quiz-feedback').append(form);}}$('quiz-feedback').hidden=false;$('quiz-submit').disabled=true;};$('quiz-next').onclick=()=>{if($('quiz-domain').value!=='wrong'||state.wrong.includes(quizCurrentUnit?.id))quizIndex++;renderQuiz();};$('quiz-export').onclick=()=>{const unit=quizCurrentUnit;if(unit)exportItemPdf(unit.title,[['主題',unit.category],['題目',displayText(unit.original_record.question??unit.title)],['選項',options(unit.original_record).map(([key,value])=>`${key}. ${displayText(value)}`).join('\n')],['正確答案',answerKeys(unit.original_record).join('、')],['解析',displayText(unit.original_record.explanation)],['來源與查證狀態',sourceText(unit)]]);};$('quiz-domain').onchange=()=>{quizIndex=0;renderQuiz();};
$('decision-form').onsubmit=event=>{event.preventDefault();const result=decision($('situation').value,$('energy').value,$('goal').value);const node=$('decision-result');node.replaceChildren(el('h3','下一步'));if(result.hints.length)node.append(el('p',`可能包含推測或評價的詞：${result.hints.join('、')}。請核對語境，這不代表你說錯。`));const list=el('ol');result.steps.forEach(step=>list.append(el('li',step)));node.append(list,el('p','事實狀態：尚未核實。此功能不推斷人格或說謊風險。'));const pdf=el('button','這次分析存成 PDF','secondary');pdf.onclick=()=>exportItemPdf('情境整理',[['狀況',$('situation').value],['精神與體力',$('energy').selectedOptions?.[0]?.textContent??$('energy').value],['希望達成',$('goal').value],['下一步',result.steps.join('\n')],['注意',`可能用詞提示：${result.hints.join('、')||'無'}。這是思考輔助，不推斷人格或說謊。`]]);node.append(pdf);node.hidden=false;};
function startEventEdit(item,date,onlyThis=false){editingEvent=onlyThis?null:item._seriesId??item.id;editingOccurrence=onlyThis?{seriesId:item._seriesId,date}:null;for(const [id,key] of [['event-title','title'],['event-start','start'],['event-end','end'],['event-category','category']])$(id).value=item[key]??'';$('event-date').value=onlyThis?date:(item.from??item.date??date);$('event-repeat').checked=!onlyThis&&item.weekday!==undefined;$('event-repeat').disabled=onlyThis;$('event-until').value=item.until??date;$('event-form-status').textContent='正在編輯：'+item.title+(onlyThis?'（只修改這一天）':'');$('detail').close();$('event-title').focus();}
function renderLoadChart(container,rows){container.replaceChildren();if(!rows.length)return;const max=Math.max(1,...rows.map(row=>row.total));for(const row of rows){const item=el('div',undefined,'load-row');const dateText=new Date(row.date+'T12:00:00+08:00').toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei',weekday:'short',month:'numeric',day:'numeric'});const total=el('strong',`${dateText} · ${(row.total/60).toFixed(1)} 小時`);const track=el('div',undefined,'load-track');track.setAttribute('role','img');track.setAttribute('aria-label',`${dateText}已排 ${(row.total/60).toFixed(1)} 小時`);const totalWidth=row.total/max*100;track.style.width=`${totalWidth}%`;for(const [category,cls] of [['course','course'],['study','study'],['rest','rest'],['deadline','other'],['personal','other']]){const minutes=row.minutes[category]??0;if(!minutes)continue;const segment=el('span',undefined,`load-segment ${cls}`);segment.style.width=`${minutes/row.total*100}%`;segment.title=`${category}：${(minutes/60).toFixed(1)} 小時`;track.append(segment);}item.append(total,track);container.append(item);}}
function renderCalendar(){if(!schedule)return;const dates=weekDates(selectedWeek);$('calendar-range').textContent=`${dates[0]} — ${dates[6]}`;renderPanorama($('week-grid'),dates,state.events,(item,date)=>{const body=$('detail-body');body.replaceChildren(el('h2',item.title),el('p',`${date} ${item.start??'全天'} ${item.end??''}`),el('p',item.notes??''));if(item.status==='draft')body.append(el('p','依文件匯入，日期與內容待核對。'));const pdf=el('button','這筆行程存成 PDF','primary');pdf.onclick=()=>exportItemPdf(item.title,[['日期',date],['時間',item.start?`${item.start}${item.end?'–'+item.end:''}`:'全天／提醒'],['類型',item.category],['備註',item.notes??''],['來源',item.source??'自行新增'],['查核狀態',item.status==='draft'?'匯入草稿，請核對':'自行新增']]);body.append(pdf);if(item._seriesId){const editOne=el('button','只修改這一天','secondary');editOne.onclick=()=>startEventEdit(item,date,true);body.append(editOne);}const edit=el('button',item._seriesId?'編輯整個週期':'編輯此事件','secondary');edit.onclick=()=>startEventEdit(item,date,false);const remove=el('button',item._seriesId?'刪除此一天':'刪除此事件','secondary');remove.onclick=()=>{if(!confirm(item._seriesId?'只刪除 '+date+' 這一天的行程？':'確認刪除此事件？'))return;state.events=item._seriesId?excludeOccurrence(state.events,item._seriesId,date):state.events.filter(e=>e.id!==item.id);save();$('detail').close();renderCalendar();};if(item._seriesId){const removeSeries=el('button','刪除整個週期','secondary');removeSeries.onclick=()=>{if(!confirm('確認刪除整個重複週期？'))return;state.events=state.events.filter(e=>e.id!==item._seriesId);save();$('detail').close();renderCalendar();};body.append(edit,remove,removeSeries);}else body.append(edit,remove);$('detail').showModal();});renderLoadChart($('calendar-load-chart'),workloadByDay(state.events,dates));const week=schedule.weeks.find(w=>dates[0]>=w.start&&dates[0]<=w.end);$('week-note').textContent=week?`第 ${week.number} 週：${week.title}。${week.focus}（文件規劃，非官方校曆）`:'一週一張全景表。跨時段事件依開始時間放入格子，時數仍計入完整事件。';$('report-date').value=selectedWeek;document.dispatchEvent(new Event('college-calendar-rendered'));}
let editingEvent=null,editingOccurrence=null;
['prev-week','next-week'].forEach(id=>$(id).onclick=()=>{const date=new Date(selectedWeek+'T12:00:00+08:00');date.setUTCDate(date.getUTCDate()+(id==='prev-week'?-7:7));selectedWeek=date.toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});renderCalendar();});$('calendar-today').onclick=()=>{selectedWeek=today;renderCalendar();};
$('import-schedule').onclick=()=>$('calendar-file').click();$('load-semester-schedule').onclick=async()=>{try{const data=await fetch('./data/schedule.json').then(r=>{if(!r.ok)throw Error('找不到內建學期課表');return r.json();});await importScheduleText(JSON.stringify(data));}catch(error){$('calendar-status').textContent='載入課表失敗：'+error.message;}};
$('calendar-file').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw new Error('作息檔不可超過 2 MB。');await importScheduleText(await file.text());}catch(error){$('calendar-status').textContent='匯入失敗：'+error.message;}finally{event.target.value='';}};
async function importScheduleText(text){if(new TextEncoder().encode(text).byteLength>2*1024*1024)throw new Error('JSON 行程資料不可超過 2 MB。');const imported=parseSchedule(text),old=new Map(state.events.map(item=>[item.id,item]));const additions=imported.events.filter(item=>!old.has(item.id)),updates=imported.events.filter(item=>old.has(item.id)&&JSON.stringify(old.get(item.id))!==JSON.stringify(item));if(updates.length&&!confirm(`這份課表將更新 ${updates.length} 個相同 ID 的行程，並新增 ${additions.length} 個。已編輯的同 ID 內容會以匯入檔為準。繼續？`))return;for(const item of imported.events)old.set(item.id,item);schedule=imported;state.schedule=imported;state.events=[...old.values()];if(imported.weeks.length){$('semester-start').value=imported.weeks[0].start;$('semester-end').value=imported.weeks.at(-1).end;}save();renderCalendar();$('calendar-status').textContent=`檢查完成：${imported.events.length} 個事件，新增 ${additions.length} 個、更新 ${updates.length} 個。日期與來源仍需自行核對；只儲存在此瀏覽器。`;}

$('load-json-example').onclick=()=>{$('schedule-json-input').value=JSON.stringify({events:[{id:'study-math-20261006',title:'微積分複習',date:'2026-10-06',start:'19:00',end:'20:00',category:'study',notes:'完成兩題例題'}],weeks:[]},null,2);};
$('import-json-text').onclick=async()=>{try{const text=$('schedule-json-input').value.trim();if(!text)throw new Error('先貼上 JSON 行程資料。');await importScheduleText(text);$('schedule-json-editor').open=false;}catch(error){$('calendar-status').textContent='匯入失敗：'+error.message;}};
$('event-form').onsubmit=event=>{event.preventDefault();const start=$('event-start').value,end=$('event-end').value;if(start&&end&&end<=start){$('calendar-status').textContent='結束時間必須晚於開始時間。';return;}const item={id:editingEvent??crypto.randomUUID(),title:$('event-title').value.trim(),date:$('event-date').value,start,end,category:$('event-category').value,status:'personal',source:'自行新增'};if($('event-repeat').checked){const until=$('event-until').value;if(!until||until<item.date){$('calendar-status').textContent='請填寫有效的重複截止日期。';return;}item.weekday=new Date(item.date+'T12:00:00Z').getUTCDay();item.from=item.date;item.until=until;delete item.date;}if(editingOccurrence){state.events=detachOccurrence(state.events,editingOccurrence.seriesId,editingOccurrence.date,item);}else{state.events=state.events.filter(e=>e.id!==item.id);state.events.push(item);}save();selectedWeek=$('event-date').value;editingEvent=null;editingOccurrence=null;$('event-repeat').disabled=false;event.target.reset();$('event-form-status').textContent='';$('event-date').value=today;renderCalendar();$('calendar-status').textContent='事件已儲存在本機瀏覽器。';};$('cancel-event-edit').onclick=()=>{editingEvent=null;editingOccurrence=null;$('event-repeat').disabled=false;$('event-form').reset();$('event-date').value=today;$('event-form-status').textContent='';};
$('copy-week').onclick=()=>{const target=$('copy-week-date').value;if(!target)return;const sourceDates=weekDates(selectedWeek),targetDates=weekDates(target);if(sourceDates[0]===targetDates[0]){$('calendar-status').textContent='請選不同的一週。';return;}const copies=sourceDates.flatMap((d,i)=>eventsOn(state.events,d).filter(e=>e.weekday===undefined).map(e=>({...e,id:crypto.randomUUID(),date:targetDates[i],source:'複製自 '+d})));if(!copies.length){$('calendar-status').textContent='本週沒有單次事件可複製；週期事件會自行延伸，不重複複製。';return;}if(!confirm(`複製 ${copies.length} 個單次事件到 ${targetDates[0]} 這週？`))return;state.events.push(...copies);save();selectedWeek=target;renderCalendar();$('calendar-status').textContent='已複製；請查看是否有時間衝突。';};
$('export-calendar').onclick=()=>{download('完整行程-匯入Google日曆.ics',toICS(state.events),'text/calendar');$('calendar-status').textContent='已匯出 ICS。可在電腦版 Google 日曆的「設定 → 匯入與匯出」選擇此檔；這是一次性匯入，不會自動同步。';};
function reportDates(){const anchor=$('report-date').value||today,mode=$('print-range').value;if(!validDate(anchor))throw new Error('請選擇有效的列印日期。');if(mode==='week')return {dates:weekDates(anchor),title:'本週行程'};if(mode==='month'){const first=anchor.slice(0,7)+'-01',end=new Date(Date.UTC(Number(anchor.slice(0,4)),Number(anchor.slice(5,7)),0)).toISOString().slice(0,10);return {dates:dateRange(first,end),title:anchor.slice(0,7)+' 月行程'};}const from=$('semester-start').value,to=$('semester-end').value;if(!validDate(from)||!validDate(to)||from>to)throw new Error('請選擇有效的學期開始與結束日期。');const days=(Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/86400000+1;if(days>200)throw new Error('列印範圍最多 200 天，請縮小學期日期。');return {dates:dateRange(from,to),title:`學期行程（${from} 至 ${to}）`};}
function dateRange(from,to){const result=[];const cursor=new Date(from+'T12:00:00Z'),end=new Date(to+'T12:00:00Z');while(cursor<=end){result.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1);}return result;}
function renderPrintReport(){const report=$('printable-calendar'),{dates,title}=reportDates();report.replaceChildren(el('p','COLLEGE OS · 個人學習行程','eyebrow'),el('h1',title),el('p',`${dates[0]} — ${dates.at(-1)} · 時區 Asia/Taipei`),el('p','以目前儲存在此瀏覽器的行程產生；匯入資料的日期與來源仍需核對。'));const loads=workloadByDay(state.events,dates);const chart=el('div',undefined,'print-load-chart');if(dates.length<=31){renderLoadChart(chart,loads);report.append(chart);}else{report.append(el('p',`完整範圍共 ${dates.length} 天；下方包含所有日期與展開後的行程。`));}const rows=[];for(const date of dates){if(!eventsOn(state.events,date).length)rows.push([date,'—','—','留白／尚無行程','']);for(const event of eventsOn(state.events,date)){rows.push([date,event.start?`${event.start}${event.end?'–'+event.end:''}`:'全天',({course:'上課',study:'讀書',rest:'休息',deadline:'考試／截止',personal:'生活／活動'})[event.category]??'其他',event.title,event.notes??'']);}}const tableNode=el('table',undefined,'data-table print-table'),head=el('tr');['日期','時間','類型','行程','備註'].forEach(text=>head.append(el('th',text)));const thead=el('thead');thead.append(head);tableNode.append(thead);const tbody=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(value=>tr.append(el('td',value)));tbody.append(tr);});tableNode.append(tbody);report.append(el('h2','行程明細'),tableNode);if(!rows.length)report.append(el('p','此期間尚無行程。'));}
$('print-range').onchange=()=>{const semester=$('print-range').value==='semester';$('semester-start-wrap').hidden=!semester;$('semester-end-wrap').hidden=!semester;};
$('print-calendar').onclick=()=>{try{renderPrintReport();$('printable-calendar').hidden=false;document.body.classList.add('print-mode');const cleanup=()=>{document.body.classList.remove('print-mode');$('printable-calendar').hidden=true;window.removeEventListener('afterprint',cleanup);};window.addEventListener('afterprint',cleanup,{once:true});setTimeout(()=>window.print(),60);setTimeout(cleanup,60000);}catch(error){$('calendar-status').textContent=error.message;}};
function rebuildKnowledge(){units=mergeKnowledge(builtinUnits,state.privateUnits??[]).map(u=>({...u,category:topicOf(u)}));questions=units.filter(u=>u.kind==='question');cards=units.map(studyCard);cardSession=[];setupKnowledge();setupCardTopics();renderLibrary();renderCard();renderQuiz();$('unit-count').textContent=units.length;$('question-count').textContent=questions.length;document.dispatchEvent(new Event('college-knowledge-changed'));}
async function init(){renderTasks();$('event-date').value=today;$('report-date').value=today;$('semester-start').value=today;$('semester-end').value=today;const errors=[];try{const manifest=await fetch('./data/index.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('找不到 data/index.json');return r.json();});const results=await Promise.allSettled(manifest.files.map(file=>loadKnowledgeFile(file)));builtinUnits=results.flatMap((result,i)=>{if(result.status==='fulfilled')return result.value;errors.push(manifest.files[i]+'：'+result.reason.message);return [];});}catch(e){errors.push(e.message);}state.privateUnits=await readKnowledge(storageKey).catch(()=>[]);rebuildKnowledge();try{const bundled=parseSchedule(JSON.stringify(await fetch('./data/schedule.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('找不到課表檔');return r.json();})));$('load-semester-schedule').hidden=!bundled.events.length;schedule=state.schedule??bundled;if(!state.schedule&&state.events.length===0&&bundled.events.length){state.schedule=bundled;state.events.push(...bundled.events);save();}if(schedule.weeks.length){$('semester-start').value=schedule.weeks[0].start;$('semester-end').value=schedule.weeks.at(-1).end;}}catch(e){schedule=state.schedule??{events:[],weeks:[]};errors.push(e.message);}renderCalendar();if(errors.length){$('load-error').hidden=false;$('load-error').textContent='部分資料未載入：'+errors.join('；')+'。已保留可用資料。請到「資料與備份」匯入完整版知識包；若直接開啟 HTML，請改用啟動檔或 GitHub Pages 網址。';}else {$('load-error').hidden=true;}}

function setupKnowledge(){const select=$('category'),old=select.value,query=$('category-search').value.trim().toLocaleLowerCase(),counts=new Map();for(const unit of units){const topic=unit.category||'未分類';counts.set(topic,(counts.get(topic)||0)+1);}select.replaceChildren();const first=el('option','所有主題');first.value='';select.append(first);[...counts].filter(([topic])=>topic.toLocaleLowerCase().includes(query)).sort((a,b)=>a[0].localeCompare(b[0],'zh-Hant')).forEach(([topic,count])=>{const option=el('option',`${topic} · ${count.toLocaleString()}`);option.value=topic;select.append(option);});select.value=counts.has(old)&&(!query||old.toLocaleLowerCase().includes(query))?old:'';renderKnowledgeDistribution();}
$('export-knowledge').onclick=()=>download('知識資料包-目前全部.json',JSON.stringify(units));
$('import-knowledge').onclick=()=>$('knowledge-file').click();$('knowledge-file').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>40e6)throw Error('知識包最多 40 MB。');$('knowledge-status').textContent='正在檢查資料…';let text;if(file.name.endsWith('.gz')){if(!globalThis.DecompressionStream)throw Error('請改選未壓縮的 JSON 資料包。');const stream=new Blob([file]).stream().pipeThrough(new DecompressionStream('gzip'));const bytes=await new Response(stream).arrayBuffer();if(bytes.byteLength>60e6)throw Error('解壓後最多 60 MB。');text=new TextDecoder().decode(bytes);}else text=await file.text();const data=validateKnowledge(JSON.parse(text)),old=new Map(units.map(u=>[u.id,u]));let added=0,updated=0;for(const u of data){if(!old.has(u.id))added++;else if(JSON.stringify(old.get(u.id))!==JSON.stringify(u))updated++;}const combined=mergeKnowledge(state.privateUnits??[],data);await writeKnowledge(storageKey,combined);state.privateUnits=combined;save();rebuildKnowledge();$('knowledge-status').textContent=`匯入完成：新增 ${added} 筆、比對有差異 ${updated} 筆（同 ID 已套用匯入內容）。目前共 ${units.length.toLocaleString()} 筆、${questions.length} 題。`;if(!errorsOnPage())$('load-error').hidden=true;}catch(error){$('knowledge-status').textContent='匯入失敗：'+error.message;}finally{event.target.value='';}};
function errorsOnPage(){return !units.length;}
async function refreshState(){schedule=state.schedule??{weeks:[],events:[]};if(state.privateUnits)await writeKnowledge(storageKey,state.privateUnits);else state.privateUnits=await readKnowledge(storageKey).catch(()=>[]);rebuildKnowledge();renderTasks();renderCalendar();document.dispatchEvent(new Event('college-saved'));document.dispatchEvent(new Event('college-state-restored'));}

await init();

if(document.body)mountExperience({getUnits:()=>units,getCards:()=>cards,getState:()=>state,getSchedule:()=>schedule,getDate:()=>selectedWeek,editEvent:(item,date)=>startEventEdit(item,date,Boolean(item._seriesId)),go:page,save,details,print:exportItemPdf,cardStart:startCardSession,cardRender:renderCard,libraryRender:renderLibrary,calendarRender:renderCalendar,quizRender:renderQuiz,quizReset:()=>{quizIndex=0;renderQuiz();},setDate:date=>{selectedWeek=date;$('report-date').value=date;renderCalendar();},importSchedule:importScheduleText});

if(document.body)mountManagement({state,save,renderTasks,go:page,print:exportItemPdf});
