import {typeNames,readable,topicOf,topicCounts} from './study.mjs';
import {eventsOn} from './calendar.mjs';
const $=id=>document.getElementById(id);
function n(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function btn(text,action,cls='secondary'){const b=n('button',text,cls);b.type='button';b.onclick=action;return b;}
const dateString=d=>d.toISOString().slice(0,10);
export function mountExperience(api){
 const {getUnits,getCards,getState}=api;
 document.querySelector('.version').textContent='新版 3.1 · 2026.10.06';
 const header=document.querySelector('main header');header.append(n('span','資料載入中','data-pill'));const pill=header.lastElementChild;
 const welcome=n('section',undefined,'setup-banner');welcome.hidden=true;welcome.append(n('div','先匯入知識資料包，就能開始搜尋、卡片與題庫。'),btn('匯入資料',()=>{api.go('settings');$('knowledge-file').click();},'primary'));document.querySelector('.heading').after(welcome);
 // Visible topic folders, with pagination rather than thousands of rows.
 const library=$('library').querySelector('.panel');const folderArea=n('section',undefined,'folder-area');folderArea.innerHTML='<div class="section-heading"><div><p class="eyebrow">你的知識資料夾</p><h2>先找主題，再看內容</h2></div><span id="folder-position"></span></div><div id="topic-folders" class="folder-grid"></div><div id="folder-pager" class="actions"></div>';
 library.prepend(folderArea);let folderPage=0;
 const toolbar=$('library').querySelector('.toolbar');toolbar.classList.add('search-toolbar');library.prepend(toolbar);
 const exportBar=n('div',undefined,'export-bar');exportBar.innerHTML='<label>PDF 從第幾筆<input id="pdf-offset" type="number" value="1" min="1"></label><label>匯出數量<select id="pdf-count"><option value="10">10 筆</option><option value="50" selected>50 筆</option><option value="100">100 筆</option><option value="all">符合條件的全部</option></select></label>';
 exportBar.append(btn('匯出這批知識 PDF',()=>{const list=filteredUnits();const start=Math.max(0,Number($('pdf-offset').value||1)-1),end=$('pdf-count').value==='all'?list.length:start+Number($('pdf-count').value),chosen=list.slice(start,end);if(!chosen.length){$('results-count').textContent='此範圍沒有資料，請調整起始筆數。';return;}api.print(`知識講義 · ${$('category').value||'全部主題'} · 第 ${start+1}–${start+chosen.length} 筆`,chosen.map((u,i)=>[`${start+i+1}. ${u.title}`,cardText(u)]));}));$('results-count').after(exportBar);
 function filteredUnits(){const q=$('search').value.toLocaleLowerCase(),cat=$('category').value,kind=$('kind').value;return getUnits().filter(u=>(!cat||topicOf(u)===cat)&&(kind==='all'||u.kind===kind)&&(!q||readable(u).toLocaleLowerCase().includes(q)));}
 function cardText(u){return `主題：${topicOf(u)}\n類型：${typeNames[u.kind]}\n\n${readable(u.core_concept)}\n${readable(u.deep_understanding)}\n${readable(u.solution_methods)}\n${readable(u.original_record)}\n\n來源：${readable(u.sources)}\n查證狀態：${u.evidence_status||'尚未查證'}`;}
 function drawFolders(){const q=$('category-search').value.toLocaleLowerCase();const rows=topicCounts(getUnits()).filter(r=>r.topic.toLocaleLowerCase().includes(q)),pages=Math.max(1,Math.ceil(rows.length/8));folderPage=Math.min(folderPage,pages-1);$('topic-folders').replaceChildren();rows.slice(folderPage*8,folderPage*8+8).forEach((row,i)=>{const b=btn('',()=>{$('category').value=row.topic;$('kind').value='all';api.libraryRender();$('results').scrollIntoView({behavior:'smooth',block:'start'});},'folder-tile');b.append(n('span','▰','folder-icon tint-'+i%4),n('strong',row.topic),n('span',`${row.total.toLocaleString()} 筆 · ${row.questions} 題`));$('topic-folders').append(b);});$('folder-position').textContent=`${rows.length} 個主題 · ${folderPage+1} / ${pages}`;const prev=btn('上一頁',()=>{folderPage--;drawFolders();}),next=btn('下一頁',()=>{folderPage++;drawFolders();});prev.disabled=folderPage===0;next.disabled=folderPage===pages-1;$('folder-pager').replaceChildren(btn('全部主題',()=>{$('category').value='';api.libraryRender();}),prev,next);}
 $('category-search').addEventListener('input',()=>{folderPage=0;drawFolders();});
 // One-click learning, visible decks and fast list browsing.
 const cardsPanel=$('cards').querySelector('.card-selector');const quick=n('div',undefined,'quick-study');quick.innerHTML='<div><p class="eyebrow">每天一小組，持續累積</p><h2>今天，學會 10 張。</h2><p id="study-progress"></p></div>';
 quick.append(btn('開始今日複習',()=>{chooseDeck('__all__');},'primary'));cardsPanel.prepend(quick);
 const decks=n('div',undefined,'deck-section');decks.innerHTML='<div class="section-heading"><h3>點選主題，直接開始</h3><span id="deck-position"></span></div><div id="deck-grid" class="folder-grid"></div><div id="deck-pager" class="actions"></div>';
 cardsPanel.querySelector('.form-grid').before(decks);decks.querySelector('#deck-grid').before(cardsPanel.querySelector('.form-grid label'));
 const advanced=n('details',undefined,'advanced-options');advanced.append(n('summary','調整主題、類型與每組張數'));cardsPanel.insertBefore(advanced,cardsPanel.querySelector('.form-grid'));advanced.append(cardsPanel.querySelector('.form-grid'));
 let deckPage=0,browsePage=0;
 const browse=n('details',undefined,'panel browse-cards');browse.innerHTML='<summary>快速瀏覽這個主題的所有卡片</summary><p>每頁 12 張；點卡片可看完整內容及單筆 PDF。</p><div id="browse-grid" class="grid"></div><div id="browse-pager" class="actions"></div>';$('cards').append(browse);
 function chooseDeck(topic){$('card-topic').value=topic;$('card-topic').onchange();if(!$('card-batch-size').value)$('card-batch-size').value='10';api.cardStart();browsePage=0;drawBrowse();$('card-study').scrollIntoView({behavior:'smooth',block:'start'});}
 function drawDecks(){const q=$('card-topic-search').value.toLocaleLowerCase(),rows=topicCounts(getCards()).filter(r=>r.topic.toLocaleLowerCase().includes(q));const pages=Math.max(1,Math.ceil(rows.length/8));deckPage=Math.min(deckPage,pages-1);$('deck-grid').replaceChildren();rows.slice(deckPage*8,deckPage*8+8).forEach((row,i)=>{const b=btn('',()=>chooseDeck(row.topic),'folder-tile');b.append(n('span','▱','folder-icon tint-'+i%4),n('strong',row.topic),n('span',`${row.total.toLocaleString()} 張 · 開始學習 →`));$('deck-grid').append(b);});$('deck-position').textContent=`${deckPage+1} / ${pages}`;const prev=btn('上一頁',()=>{deckPage--;drawDecks();}),next=btn('下一頁',()=>{deckPage++;drawDecks();});prev.disabled=!deckPage;next.disabled=deckPage>=pages-1;$('deck-pager').replaceChildren(prev,next);}
 function drawBrowse(){const topic=$('card-topic').value,kind=$('card-kind').value;const list=getCards().filter(u=>(!topic||topic==='__all__'||topicOf(u)===topic)&&(kind==='all'||u.kind===kind));const pages=Math.max(1,Math.ceil(list.length/12));browsePage=Math.min(browsePage,pages-1);$('browse-grid').replaceChildren();list.slice(browsePage*12,browsePage*12+12).forEach(u=>{const b=btn('',()=>api.details(u),'unit');b.append(n('span',typeNames[u.kind],'tag'),n('h3',u.title),n('p',readable(u.back).slice(0,110)));$('browse-grid').append(b);});const prev=btn('上一頁',()=>{browsePage--;drawBrowse();}),next=btn('下一頁',()=>{browsePage++;drawBrowse();});prev.disabled=!browsePage;next.disabled=browsePage>=pages-1;$('browse-pager').replaceChildren(prev,n('span',`${browsePage+1} / ${pages} · ${list.length} 張`),next,btn('這頁卡片 PDF',()=>api.print('卡片複習講義',list.slice(browsePage*12,browsePage*12+12).map(u=>[u.title,cardText(u)]))));}
 $('card-topic-search').addEventListener('input',()=>{deckPage=0;drawDecks();});$('card-topic').addEventListener('change',()=>{browsePage=0;drawBrowse();});$('card-kind').addEventListener('change',()=>{browsePage=0;drawBrowse();});
 $('card-study').querySelector('.study-note').append(n('p','鍵盤：空白鍵翻面 · 1 再練 · 2 記住 · → 跳過。記住後依 1、3、7、14、30 天安排複習；再練為 10 分鐘後。'));
 // Quiz choices come from actual data, not hardcoded filenames.
 const quizToolbar=$('quiz').querySelector('.toolbar');const qSearch=n('input');qSearch.id='quiz-search';qSearch.type='search';qSearch.placeholder='搜尋題目關鍵字';qSearch.setAttribute('aria-label','搜尋題目關鍵字');quizToolbar.prepend(qSearch);qSearch.oninput=()=>api.quizReset();
 const qSummary=n('p',undefined,'data-summary');qSummary.id='quiz-data-summary';quizToolbar.before(qSummary);
 function drawQuiz(){const select=$('quiz-domain'),old=select.value;select.replaceChildren();for(const [value,label] of [['all','全部題目'],['wrong','我的錯題']]){const o=n('option',label);o.value=value;select.append(o);}topicCounts(getUnits().filter(u=>u.kind==='question')).forEach(row=>{const o=n('option',`${row.topic}（${row.total} 題）`);o.value='topic:'+row.topic;select.append(o);});select.value=[...select.options].some(o=>o.value===old)?old:'all';$('quiz-data-summary').textContent=`已載入 ${getUnits().filter(u=>u.kind==='question').length} 道獨立題目 · ${getState().wrong.length} 道錯題 · 可依實際主題篩選`;api.quizRender();}
 // Calendar has week, month and all dates in the semester.
 const calPanel=$('calendar').querySelector('.panel');const switcher=n('div',undefined,'calendar-navigation');switcher.innerHTML='<div class="segmented" role="group" aria-label="日曆檢視"><button type="button" data-view="week" class="selected">週</button><button type="button" data-view="month">月</button><button type="button" data-view="semester">完整學期</button></div><label>跳到日期<input id="calendar-jump" type="date"></label>';
 calPanel.prepend(switcher);let view='week',agendaPage=0;const alternate=n('div');alternate.id='calendar-alternate';calPanel.querySelector('.calendar-scroll').after(alternate);
 const advancedCal=n('details',undefined,'calendar-tools');advancedCal.append(n('summary','匯入、匯出 PDF、Google 日曆與其他工具'));switcher.after(advancedCal);advancedCal.append(calPanel.querySelector('.toolbar'),$('schedule-json-editor'));const printQuick=btn('匯出目前日期表 PDF',()=>{if(view==='semester'){$('print-range').value='semester';}else {$('print-range').value=view;}$('print-range').onchange();$('print-calendar').click();});switcher.append(btn('＋ 新增行程',()=>{$('event-date').value=api.getDate();$('event-form').scrollIntoView({behavior:'smooth'});$('event-title').focus();},'primary'),printQuick);const periodNav=n('div',undefined,'calendar-paging');const periodLabel=n('strong');function shiftPeriod(direction){if(view==='semester'){agendaPage=Math.max(0,agendaPage+direction);drawCalendar();return;}const d=new Date(api.getDate()+'T12:00:00Z');if(view==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+direction);}else d.setUTCDate(d.getUTCDate()+direction*7);api.setDate(dateString(d));}periodNav.append(btn('← 上一期',()=>shiftPeriod(-1)),periodLabel,btn('下一期 →',()=>shiftPeriod(1)),btn('今天',()=>api.setDate(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}))));switcher.after(periodNav);
 switcher.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;agendaPage=0;switcher.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('selected',x===b));drawCalendar();});$('calendar-jump').value=api.getDate();$('calendar-jump').onchange=()=>{if($('calendar-jump').value)api.setDate($('calendar-jump').value);};
 function showEvent(item,date){const body=$('detail-body');body.replaceChildren(n('span',date,'tag'),n('h2',item.title),n('p',`${item.start||'全天'}${item.end?'–'+item.end:''}`),n('p',item.notes||''),btn('這筆行程 PDF',()=>api.print(item.title,[['日期',date],['時間',`${item.start||'全天'} ${item.end||''}`],['備註',item.notes]])),btn('編輯這一天',()=>{$('detail').close();api.editEvent(item,date);$('event-form').scrollIntoView({behavior:'smooth'});}));$('detail').showModal();}
 function drawCalendar(){const date=api.getDate();periodLabel.textContent=view==='semester'?'完整學期':view==='month'?date.slice(0,7):$('calendar-range').textContent;$('calendar-jump').value=date;calPanel.querySelector('.calendar-scroll').hidden=view!=='week';calPanel.querySelector('.load-chart-section').hidden=view!=='week';alternate.hidden=view==='week';alternate.replaceChildren();if(view==='week')return;if(view==='month'){const start=new Date(date.slice(0,7)+'-01T12:00:00Z');start.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);const grid=n('div',undefined,'month-grid');['一','二','三','四','五','六','日'].forEach(day=>grid.append(n('strong','週'+day,'month-heading')));for(let i=0;i<42;i++){const d=dateString(start),cell=n('div',undefined,'month-cell'+(d.slice(0,7)!==date.slice(0,7)?' muted':''));const jump=btn(String(start.getUTCDate()),()=>{api.setDate(d);view='week';switcher.querySelector('[data-view="week"]').click();});cell.append(jump);const entries=eventsOn(getState().events,d);entries.slice(0,3).forEach(e=>cell.append(btn((e.start||'全天')+' '+e.title,()=>showEvent(e,d),'mini-event '+e.category)));if(entries.length>3)cell.append(btn('另 '+(entries.length-3)+' 筆',()=>{api.setDate(d);switcher.querySelector('[data-view="week"]').click();},'more-day'));grid.append(cell);start.setUTCDate(start.getUTCDate()+1);}alternate.append(n('h2',date.slice(0,7)+' 月'),grid);return;}
 const sch=api.getSchedule(),from=sch?.weeks?.[0]?.start||$('semester-start').value,to=sch?.weeks?.at(-1)?.end||$('semester-end').value;const dates=[];for(let d=new Date(from+'T12:00:00Z');d<=new Date(to+'T12:00:00Z')&&dates.length<366;d.setUTCDate(d.getUTCDate()+1))dates.push(dateString(d));const pages=Math.max(1,Math.ceil(dates.length/14));agendaPage=Math.min(agendaPage,pages-1);alternate.append(n('h2',`完整日期表 · ${from} 至 ${to}`),n('p',`共 ${dates.length} 天，包含没有行程的日期。第 ${agendaPage+1} / ${pages} 頁`));const list=n('div',undefined,'agenda');dates.slice(agendaPage*14,agendaPage*14+14).forEach(d=>{const row=n('section',undefined,'agenda-day');row.append(n('h3',d+' '+new Date(d+'T12:00:00Z').toLocaleDateString('zh-TW',{weekday:'long'})));const entries=eventsOn(getState().events,d);if(!entries.length)row.append(n('p','留白／尚無行程'));entries.forEach(e=>row.append(btn(`${e.start||'全天'}${e.end?'–'+e.end:''}　${e.title}`,()=>showEvent(e,d),'agenda-event '+e.category)));list.append(row);});alternate.append(list);const pager=n('div',undefined,'actions'),prev=btn('前 14 天',()=>{agendaPage--;drawCalendar();}),next=btn('後 14 天',()=>{agendaPage++;drawCalendar();});prev.disabled=!agendaPage;next.disabled=agendaPage>=pages-1;pager.append(prev,next);alternate.append(pager);}
 document.addEventListener('college-calendar-rendered',drawCalendar);
 // Shortcuts are active only outside form inputs.
 document.addEventListener('keydown',event=>{if(event.target.matches('input,textarea,select')||document.querySelector('dialog[open]'))return;if(!$('cards').hidden&&!$('card-study').hidden){const action={' ':'flip','1':'card-again','2':'card-known','ArrowRight':'card-next'}[event.key];if(action){event.preventDefault();$(action).click();}}});
 function refresh(){pill.textContent=`${getUnits().length.toLocaleString()} 筆知識 · ${getUnits().filter(u=>u.kind==='question').length} 題`;welcome.hidden=!!getUnits().length;drawFolders();drawDecks();drawBrowse();drawQuiz();progress();}
 function progress(){const now=new Date().toISOString(),due=getCards().filter(u=>!getState().reviewDue[u.id]||getState().reviewDue[u.id].due<=now).length;const known=Object.values(getState().mastery).filter(x=>x==='known').length;$('study-progress').textContent=`${getCards().length.toLocaleString()} 張可學習 · ${due.toLocaleString()} 張未學／到期 · ${known} 張已掌握`;}
 document.addEventListener('college-knowledge-changed',refresh);document.addEventListener('college-saved',progress);refresh();drawCalendar();
}
