import {buildCoachPrompt,makeLearningRecord,STUDY_STEPS} from './learning-method.mjs?v=3.8';
import {topicOf,readable} from './study.mjs?v=3.5';

const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};

export function mountLearningLab({state,save,getUnits,go}){
  state.learningSessions??=[];
  const nav=document.querySelector('nav');
  const navButton=el('button','✦ AI × NLP 學習SOP');navButton.type='button';navButton.dataset.page='learning-lab';navButton.onclick=()=>go('learning-lab');
  const cardsButton=nav.querySelector('[data-page="cards"]');cardsButton.after(navButton);
  const page=el('section');page.id='learning-lab';page.className='page learning-lab';page.hidden=true;
  page.innerHTML=`<div class="panel learning-intro"><p class="eyebrow">一套流程，讀課程也讀自己的知識庫</p><h2>把「看過」變成「能說、能做、能遷移」。</h2><p>先閉卷診斷，再用最少材料補缺口；接著提取、解題、換情境應用，最後安排複習。這裡會在本機整理 AI 提示詞，不會自動傳送教材或呼叫 AI。</p><div class="learning-pills"><span>來源先行</span><span>主動回想</span><span>刻意練習</span><span>間隔複習</span></div></div>
  <div class="panel"><div class="section-heading"><div><p class="eyebrow">開始一輪 15–40 分鐘的學習</p><h2>① 選主題與材料</h2></div><span id="learning-knowledge-count" class="tag"></span></div>
   <div class="form-grid"><label>學習方式<select id="learning-mode"><option>課程／考試</option><option>知識庫／概念理解</option><option>自然語言處理（NLP）</option></select></label><label>課程／領域<input id="learning-subject" maxlength="100" placeholder="例如：微積分、管理學、iPAS AI 應用規劃"></label><label>知識主題<select id="learning-topic"><option value="">先選主題（可只用課程材料）</option></select></label><label>本次目標<input id="learning-goal" maxlength="240" placeholder="例如：能說明梯度方向並完成一道題"></label></div>
   <details class="learning-units"><summary>從我的知識庫挑選卡片（最多 5 張）</summary><p>只會把你勾選的卡片摘要放進提示詞；題庫問題不會自動展開。</p><div id="learning-unit-list" class="learning-unit-list"></div><p id="learning-unit-status" role="status"></p></details>
   <label class="learning-wide">課程教材／自己的筆記／考題<textarea id="learning-material" maxlength="12000" rows="7" placeholder="可貼老師投影片重點、課程目標、自己的筆記或一題作業。資料只留在本機頁面；產生提示詞後，由你決定是否複製到外部 AI。"></textarea></label>
   <label class="learning-wide">現在卡住的題目或問題<textarea id="learning-question" maxlength="3000" rows="3" placeholder="例如：我會套公式，但不懂為什麼要對 x 微分。"></textarea></label>
  </div>
  <div class="panel"><div class="section-heading"><div><p class="eyebrow">②–⑥ 照順序執行</p><h2>學習 SOP</h2></div><span id="learning-step-progress" class="tag">0 / 6 步</span></div><div id="learning-steps" class="learning-steps"></div>
    <div class="learning-grid"><label>閉卷診斷：不看資料，我現在記得什麼？<textarea id="learning-diagnosis" rows="4" maxlength="2500" placeholder="先關上教材，寫出你能說明的部分，以及最不確定的一點。"></textarea></label><label>我最關鍵的缺口／混淆點<textarea id="learning-gap" rows="4" maxlength="1500" placeholder="例如：把條件機率和聯合機率混為一談。"></textarea></label><label>做完回想、題目或遷移練習後，我的回答<textarea id="learning-reflection" rows="4" maxlength="2500" placeholder="用自己的話回答，不要貼 AI 的答案。"></textarea></label><label>自評：閉卷解釋和應用到哪裡？<select id="learning-score"><option value="0">尚未確認</option><option value="1">1｜能認出，還說不完整</option><option value="2">2｜能閉卷解釋，但新題會卡</option><option value="3">3｜能閉卷解釋並處理新情境</option></select></label><label>下次複習<input id="learning-review-date" type="date"></label></div>
   <div class="learning-actions"><button id="learning-build-prompt" type="button" class="primary">產生我的 AI 教練提示詞</button><button id="learning-save" type="button" class="secondary">儲存本次學習紀錄</button></div><p class="privacy-note">提示詞只在本機產生。按下「複製」才會放進剪貼簿；之後是否貼到 ChatGPT、NotebookLM 或其他 AI，由你自己決定。課程資料有個資或保密限制時，請先刪除敏感內容。</p><p id="learning-status" role="status"></p>
   <div id="learning-prompt-wrap" class="learning-prompt-wrap" hidden><label>AI 提示詞<textarea id="learning-prompt" rows="16" readonly></textarea></label><button type="button" id="learning-copy-prompt" class="secondary">複製提示詞</button><p id="learning-copy-status" role="status"></p></div>
  </div>
  <div class="panel"><div class="section-heading"><div><p class="eyebrow">下次用新的題目驗證</p><h2>學習紀錄與待複習</h2></div><span id="learning-history-summary" class="tag"></span></div><div id="learning-due-list" class="learning-history"></div><details><summary>查看最近的學習紀錄</summary><div id="learning-history-list" class="learning-history"></div></details></div>
  <div class="panel learning-note"><h3>此處的「NLP」是什麼？</h3><p>自然語言處理（Natural Language Processing）：把教材文字拆成術語、概念關係、步驟與題目，再由你對照原始來源、閉卷回想並應用。網站不內建大型語言模型；AI 回答也必須回到原文核對。這和「神經語言程式學」是不同用語，本工具不把後者當成已證實的快速學習法。</p><p><strong>AI 學習順序：</strong>先自己嘗試 → 請 AI 追問與提示 → 自己修正 → 闔上 AI 再重建一次 → 隔天換題驗證。只讀 AI 整理出的摘要不算掌握。</p></div>`;
  document.querySelector('main footer').before(page);

  const topics=()=>[...new Set(getUnits().map(topicOf).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));
  function renderTopics(){const select=$('learning-topic'),prev=select.value;select.replaceChildren(new Option('先選主題（可只用課程材料）',''));topics().forEach(t=>select.add(new Option(t,t)));if(topics().includes(prev))select.value=prev;$('learning-knowledge-count').textContent=`知識庫 ${getUnits().length.toLocaleString()} 筆`;
    renderUnits();}
  function renderUnits(){const list=$('learning-unit-list'),topic=$('learning-topic').value;list.replaceChildren();if(!topic){list.append(el('p','先選一個知識主題，才會列出可挑選的卡片。','empty'));return;}const units=getUnits().filter(u=>topicOf(u)===topic&&u.kind!=='question');if(!units.length){list.append(el('p','這個主題目前沒有概念型卡片，可直接貼上課程材料。','empty'));return;}units.slice(0,40).forEach(u=>{const label=el('label',undefined,'learning-unit');const input=el('input');input.type='checkbox';input.value=u.id;input.onchange=()=>{const selected=list.querySelectorAll('input:checked');if(selected.length>5){input.checked=false;$('learning-unit-status').textContent='每次最多選 5 張，先從本次要學的重點開始。';}else $('learning-unit-status').textContent=`已選 ${selected.length} / 5 張。`;};label.append(input,el('span',u.title||readable(u.core_concept).slice(0,55)),el('small',u.kind||'知識卡'));list.append(label);});if(units.length>40)list.append(el('p',`此主題有 ${units.length} 張卡，先顯示前 40 張；建議用知識庫縮小到當前章節。`,'chart-caption'));}
  $('learning-topic').onchange=renderUnits;document.addEventListener('college-knowledge-changed',renderTopics);
  renderTopics();
  const tomorrow=new Date(Date.now()+86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});$('learning-review-date').value=tomorrow;
  const steps=$('learning-steps');STUDY_STEPS.forEach(item=>{const row=el('label',undefined,'learning-step');const check=el('input');check.type='checkbox';check.dataset.step=item.id;check.onchange=updateStepCount;const copy=el('span',undefined,'learning-step-copy');copy.append(el('strong',item.title),el('small',item.minutes+' · '+item.why),el('span',item.action));row.append(check,copy);steps.append(row);});
  function updateStepCount(){const n=steps.querySelectorAll('input:checked').length;$('learning-step-progress').textContent=`${n} / 6 步已完成`;}
  $('learning-build-prompt').onclick=()=>{const chosen=[...$('learning-unit-list').querySelectorAll('input:checked')].map(x=>getUnits().find(u=>u.id===x.value)).filter(Boolean);const safe=chosen.map(u=>({title:u.title,core_concept:readable(u.core_concept),deep_understanding:readable(u.deep_understanding),solution_methods:readable(u.solution_methods),sources:u.sources}));$('learning-prompt').value=buildCoachPrompt({mode:$('learning-mode').value,subject:$('learning-subject').value,topic:$('learning-topic').value,goal:$('learning-goal').value,diagnosis:$('learning-diagnosis').value,question:$('learning-question').value,material:$('learning-material').value,knowledge:safe});$('learning-prompt-wrap').hidden=false;$('learning-status').textContent='提示詞已在本機產生。先檢查內容與隱私，再自行決定是否複製給外部 AI。';$('learning-prompt').focus();};
  $('learning-copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText($('learning-prompt').value);$('learning-copy-status').textContent='已複製。請先確認貼上的 AI 工具符合你的資料隱私需求。';}catch{$('learning-prompt').focus();$('learning-prompt').select();$('learning-copy-status').textContent='瀏覽器未授權剪貼簿；已選取文字，請手動複製。';}};
  $('learning-save').onclick=()=>{const subject=$('learning-subject').value.trim(),topic=$('learning-topic').value,diagnosis=$('learning-diagnosis').value.trim(),reviewDate=$('learning-review-date').value;if(!subject&&!topic){$('learning-status').textContent='請填課程／領域或選一個知識主題，再儲存紀錄。';return;}if(!diagnosis){$('learning-status').textContent='先完成閉卷診斷，再儲存，紀錄才看得出學習缺口。';$('learning-diagnosis').focus();return;}const record=makeLearningRecord({subject,topic,mode:$('learning-mode').value,goal:$('learning-goal').value,diagnosis,gap:$('learning-gap').value,reflection:$('learning-reflection').value,score:$('learning-score').value,reviewDate,steps:[...steps.querySelectorAll('input')].map(x=>x.checked)});state.learningSessions.unshift(record);state.learningSessions=state.learningSessions.slice(0,300);save();$('learning-status').textContent='已儲存在這台瀏覽器，並會包含於「匯出完整備份」。';renderHistory();};
  function renderHistory(){const rows=state.learningSessions??[],due=rows.filter(x=>x.reviewDate&&x.reviewDate<=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}));$('learning-history-summary').textContent=`${rows.length} 次紀錄 · ${due.length} 項待複習`;$('learning-due-list').replaceChildren();if(!due.length)$('learning-due-list').append(el('p','目前沒有到期複習；安排明天或幾天後再做一次閉卷回想。','empty'));due.slice(0,12).forEach(row=>{$('learning-due-list').append(historyRow(row,true));});$('learning-history-list').replaceChildren();if(!rows.length)$('learning-history-list').append(el('p','完成一輪後，這裡會留下主題、缺口與下次複習日。','empty'));rows.slice(0,30).forEach(row=>$('learning-history-list').append(historyRow(row,false)));}
  function historyRow(row,isDue){const box=el('article',undefined,'learning-record');box.append(el('strong',`${row.topic||row.subject} · ${row.date}`),el('span',`閉卷自評 ${row.score||0}/3 · ${row.completedSteps?.length||0}/6 步${row.reviewDate?' · 複習 '+row.reviewDate:''}`));if(row.gap)box.append(el('p','待補缺口：'+row.gap));if(isDue){const done=el('button','我已完成本次複習','secondary');done.type='button';done.onclick=()=>{row.reviewDate='';row.reflection=(row.reflection?row.reflection+'\n':'')+'複習完成 '+new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});save();renderHistory();};box.append(done);}return box;}
  renderHistory();return {renderTopics,renderHistory};
}
