import {parseSchedule} from './calendar.mjs';
export const localDate=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
export function validDate(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;}
export function amountCents(value){const text=String(value).trim();if(!/^\d+(\.\d{1,2})?$/.test(text))throw Error('金額需為正數，最多兩位小數。');const [a,b='']=text.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n<=0||n>1e11)throw Error('金額超出範圍。');return n;}
export function migrate(state){state.schemaVersion=2;for(const key of ['plans','logs','transactions','reviews','attempts','adjustments'])state[key]??=[];state.budgets??={};state.openingCents??=0;state.reviewDue??={};return state;}
export function weeklyReport(state,dates){const selected=state.logs.filter(x=>dates.includes(x.date));const reasons={};for(const log of selected)if(log.status!=='done')reasons[log.reason||'尚未填原因']=(reasons[log.reason||'尚未填原因']||0)+1;const tasks=dates.flatMap(d=>state.tasks[d]??[]);const attempts=state.attempts.filter(a=>dates.includes(a.date));return {logs:selected,days:dates.map(date=>({date,planned:selected.filter(x=>x.date===date).reduce((s,x)=>s+x.planned,0),actual:selected.filter(x=>x.date===date).reduce((s,x)=>s+x.actual,0)})),done:selected.filter(x=>x.status==='done').length,total:selected.length,taskDone:tasks.filter(x=>x.done).length,taskTotal:tasks.length,reasons,attempts,correct:attempts.filter(a=>a.correct).length};}
export function moneySummary(transactions,month,opening=0){const all=transactions.reduce((s,t)=>s+(t.type==='income'?t.cents:-t.cents),opening);const chosen=transactions.filter(t=>t.date.startsWith(month));return {balance:all,income:chosen.filter(t=>t.type==='income').reduce((s,t)=>s+t.cents,0),expense:chosen.filter(t=>t.type==='expense').reduce((s,t)=>s+t.cents,0),categories:chosen.filter(t=>t.type==='expense').reduce((o,t)=>(o[t.category]=(o[t.category]||0)+t.cents,o),{})};}
export function planProgress(plan){if(plan.status==='done')return 100;return Math.min(100,Math.max(0,Math.round((Number(plan.current)||0)/(Number(plan.target)||1)*100)));}
export function validateKnowledge(data){if(!Array.isArray(data)||data.length>10000||data.some(u=>!u||typeof u.id!=='string'||typeof u.title!=='string'||!Array.isArray(u.sources)||!u.original_record||typeof u.original_record!=='object'||!['concept','question','note','flashcard','research','formula'].includes(u.kind)))throw Error('需要統一格式的知識單元陣列。');if(new Set(data.map(u=>u.id)).size!==data.length)throw Error('知識包內有重複 ID。');for(const u of data)if(u.kind==='flashcard'&&(typeof u.original_record.front!=='string'||typeof u.original_record.back!=='string'))throw Error('翻讀卡需要正反面。');return data;}
export function validateBackup(text){const value=JSON.parse(text);const state=value.state??value;if(!state||typeof state!=='object'||Array.isArray(state)||!state.tasks||typeof state.tasks!=='object'||Array.isArray(state.tasks))throw Error('不是 College OS 備份。');if(state.schemaVersion>2)throw Error('備份版本較新，請先更新程式。');for(const key of ['wrong','events','plans','logs','transactions','reviews','attempts','adjustments'])if(state[key]!==undefined&&!Array.isArray(state[key]))throw Error('備份欄位格式錯誤：'+key);for(const [day,tasks] of Object.entries(state.tasks)){if(!validDate(day)||!Array.isArray(tasks)||tasks.length>4||tasks.some(t=>typeof t.title!=='string'||typeof t.done!=='boolean'))throw Error('任務格式錯誤。');}for(const t of state.transactions??[])if(!validDate(t.date)||!['income','expense'].includes(t.type)||!Number.isSafeInteger(t.cents)||t.cents<=0||typeof t.category!=='string')throw Error('收支資料格式錯誤。');for(const x of state.logs??[])if(!validDate(x.date)||typeof x.title!=='string'||!['done','partial','cancelled'].includes(x.status)||![x.planned,x.actual].every(n=>Number.isFinite(n)&&n>=0&&n<=1440))throw Error('紀錄格式錯誤。');for(const x of state.plans??[])if(typeof x.title!=='string'||!validDate(x.due)||!Number.isFinite(x.target)||x.target<=0||!Number.isFinite(x.current)||x.current<0)throw Error('目標格式錯誤。');if(state.events)parseSchedule(JSON.stringify({events:state.events,weeks:state.schedule?.weeks??[]}));if(state.privateUnits)validateKnowledge(state.privateUnits);if(state.openingCents!==undefined&&(!Number.isSafeInteger(state.openingCents)||state.openingCents<0))throw Error('期初金額不正確。');for(const value of Object.values(state.budgets??{}))if(!Number.isSafeInteger(value)||value<0)throw Error('預算不正確。');for(const x of state.reviews??[])if(!validDate(x.week)||!Array.isArray(x.changes)||typeof x.good!=='string'||typeof x.problem!=='string')throw Error('回顧格式錯誤。');for(const x of state.adjustments??[])if(typeof x.text!=='string'||typeof x.outcome!=='string')throw Error('調整紀錄格式錯誤。');return migrate(state);}
